name: Conventional commit compliance

on: [push]

concurrency:
  group: conventional-commits-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  cog_check_job:
    runs-on: ubuntu-latest
    name: check conventional commit compliance
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Conventional commit check
        uses: cocogitto/cocogitto-action@c7a74f5406bab86da17da0f0e460a69f8219a68c # v3
